project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute: 
  freeze: auto

website:
  title: "SciComp Workshop - Creating Websites with Quarto"
  favicon: images/logos/hex_scicomptools.png
  repo-url: https://github.com/lter/workshop-quarto
  repo-actions: [issue]
  navbar:
    background: primary
    right: 
      - text: "SciComp Team"
        menu:
          - href: https://lter.github.io/scicomp/
            text: "Home"
          - href: https://lter.github.io/scicomp/staff.html
            text: "People"
      - icon: github
        href: https://github.com/lter/workshop-quarto
  sidebar:
    style: "docked"
    background: secondary
    search: true
    contents: 
      - text: "Workshop Home"
        href: index.qmd
      - section: "Create"
        contents:
         - text: "Quarto Background"
           href: background.qmd
         - text: "Make Structure"
           href: create.qmd
         - text: "Deploy via GitHub"
           href: deploy.qmd
      - section: "Edit"
        contents: 
         - text: "Add a Page"
           href: add.qmd
         - text: "Edit via GitHub"
           href: add.qmd
         - text: "Customize a Website"
           href: customize.qmd
  page-footer: 
    center: "Copyright 2025, LTER Network"
    background: secondary
  margin-footer: |
    <img src="images/logos/nceas.png" alt="Logo for NCEAS (National Center for Ecological Analysis and Synthesis)" width="40%"/>
    <img src="images/logos/lter.png" alt="Logo for the LTER Network Office" width="40%"/>

format:
  html:
    code-overflow: scroll
    code-line-numbers: false
    code-annotations: hover
    code-copy: true
    theme:
       light: _extensions/lter/lter_scss-theme/theme_lter-edu-light.scss
       dark: _extensions/lter/lter_scss-theme/theme_lter-edu-dark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false

editor: source